### ISSUE TITLE
"wrong" VAT calculation on Mollie API results in declined order

### ISSUE THREAD

**Issue by hw-dwalter** [mollie/Shopware6#37]
We discovered the following issue with some orders:
```
> Could not create Mollie order, error: Error executing API call (422: Unprocessable Entity):
> Order line 3 is invalid. VAT amount is off.
> Expected VAT amount to be -€0.54 (-€3.95 × (16.00% / 116.00%)), got -€0.55.
> Field: lines.3.vatAmount.
```
This is the corresponding shopping cart in our shopware 6:
![image](https://user-images.githubusercontent.com/1303452/95340095-0cb19700-08b5-11eb-8011-adaa8b2e2e9f.png)

I have debugged the data sent to mollie API. This numbers are sent to mollie:
![image](https://user-images.githubusercontent.com/1303452/95338132-e3900700-08b2-11eb-8839-68ac941330be.png)

This means that Mollie calculates the VAT of the 5% discount from the unit price and not from the VAT Amount of the main article!

Here again the mathematics behind it:

- Shopware
    - -€10.90 × (5.00% / 100.00%) = **-€0.55**
- Molly
    - -€3.95 × (16.00% / 116.00%) = **-€0.54**

As a result, Mollie refuses this order. The order does not reach Mollie. It is not visible in the dashboard. In the shopware these orders are stored with the payment status "Open" and without Mollie Order ID.

The problem of different mathematics seems to be the "horizontal VAT" or "vertical VAT". calculation. More information about this here https://rolandtapken.de/blog/2008-08/mwst-berechnung-von-lexware-buero-easy (only german)

However, this is the only way to determine the sum of the individual VAT amounts. values is correct. So **10,90€ - 0,33€ -0,55€ = 10,02€**

The error is therefore to be found in Mollie or the Shopware6 plugin from Mollie and probably not in the Shopware itself.

Temporarily I changed the math in shopware core in this file to get rid of this error:
https://github.com/shopware/platform/blob/master/src/Core/Checkout/Cart/Price/PercentagePriceCalculator.php#L46
But this will only help in case of percentage discounts and is far away from perfekt!

**Comment by milan-kiener** [comment]
Hi! We are working on a possible fix for this. We'll keep you posted on this.

**Comment by milan-kiener** [comment]
@hw-dwalter Just so you know, we are still working on this. We'll keep you posted.

**Comment by AndreasA** [comment]
I also had an issue with totals being not valid. probably do to something similar regarding rounding ?

**Comment by AndreasA** [comment]
Current shopware versions have a selection regarding tax calculation per sales channel. However, I think this will not fix it as it would still fail as it differs between tax of total and tax per position.

In my case: https://github.com/mollie/Shopware6/issues/42
I have similar issues with one item but that items is a bit complicated with two depths of child item add using custom cart processors etc.

However, I am actually a bit surprised that mollie checks the data sent to it.

**Comment by AndreasA** [comment]
Btw. our team did not encounter this with discounts but just products. As mentioned they are a bit more complicated and I guess the data sent to mollie might not be rounded by the plugin at all. so if the calculated tax was 0.165, it will be cut to 0.16 in this method:
\Kiener\MolliePayments\Service\OrderService::getPriceArray

The rounding is usually done just before output to avoid a lot of rounding precision errors, if further calculation is necessary.

**Comment by AndreasA** [comment]
My issue might be related to the following:
- My main item price calculates from various child items.
- So due to taxes being calculated per child item and summed up, there might be a rounding difference here.
- Not sure how to best proceed with this regarding mollie ?

**Comment by AndreasA** [comment]
Another question how does mollie and the plugin handle multiple tax rates? Especially, if a line item has multiple tax rates which actually is a valid scenario as you could have a combined item which is split between reduced and normal tax. 

With the code here, I personally doubt that such a calcuation will ever result in the correct data:
https://github.com/mollie/Shopware6/blob/master/src/Service/OrderService.php#L334


And here `round($tax[self::TAX_ARRAY_KEY_TAX_RATE], 4) * 100` I think you should first do the `* 100` and then the rounding as another floating point calculation can have floating point imprecision, so e.g. this could result in something like `19.9999999999999997`.

**Comment by milan-kiener** [comment]
@hw-dwalter We might have find the cause for this. We are aiming on a release tomorrow morning, would you be able to test it afterwards?

**Comment by hw-dwalter** [comment]
Sounds great! Of course, I can test it!

**Comment by AndreasA** [comment]
@milan-kiener
 Will this fix also fix the tax issue with summed up child items? Tax calculation is rounded per item, so it might be different from a directly calculated tax.

If so, I will definitely try it too.

**Comment by milan-kiener** [comment]
@hw-dwalter @AndreasA We've released 1.3.6 last Friday. Please try out the release for yourself and let us know if you are satisfied with the solution.

**Comment by AndreasA** [comment]
@milan-kiener Thanks for the information. I will probably try it sometime next week.

**Comment by hw-dwalter** [comment]
I have tested version 1.3.6 with the exact products, prices and coupons as in the first screenshot in this ticket. Problem is not fixed:
![image](https://user-images.githubusercontent.com/1303452/99770380-0c3d2a80-2b08-11eb-96ed-d8154b519a3f.png)

I have pulled the 1.3.6 branch, updated composer stuff and performed the shopware cli plugin update like this: `bin/console plugin:update MolliePayments`. Did I missed something?

**Comment by AndreasA** [comment]
I had a similar issue with summing up child item prices and from what I see something similar is used in discount calculation. As far as I understand the plugin developers are getting in touch with Shopware regarding this.

What I did was to recalculate the taxes correctly with a custom cart processor by going through the items, using the total and the tax rate and recalculating it. It is relatively straight forward. This way I was able to fix the issues.

Would be better of course, if Shopware (or the plugin) would fix this but I think it is actually a Shopware issue.

**Comment by AndreasA** [comment]
@hw-dwalter Btw. did you try if e.g. using vertical tax calculation method will fix your issue as the tax is calculated at the end? Not sure though, if mollie actually supports that method and if you are allowed to use it in your country.
