### ISSUE TITLE
Cancel payment leads to PaymentException

### ISSUE THREAD

**Issue by jackyraimond** [mollie/Shopware6#807]
If I'm cancelling an payment I'm redirected to the webshop again and I can see an error 500 message:

```json
{
  "errors": [
    {
      "code": "0",
      "status": "500",
      "title": "Internal Server Error",
      "detail": "Undefined constant Shopware\\Core\\Checkout\\Payment\\PaymentException::PAYMENT_CUSTOMER_CANCELED_EXTERNAL"
    }
  ]
}
```

**Comment by BlackScorp** [comment]
Hello Thx for pointing that out. We already addressed this issue and it will be fixed in upcoming release.

The problem here is within our polyfill classes. in order to ensure that the plugin is working on different shopware versions, we created polyfill classes which comes in place if a current shopware version does not provide it. 

the autoloading process in PHP however finds sometimes our polyfill class instead of the original shopware class and then a wrong class is included int he code.

i fixed this with this commit. https://github.com/mollie/Shopware6/commit/8b3253b99887ee50464051d6e9675cc773c3a9b5. maybe you can apply it to your code base until the new version is released so you dont have the error in the meantime

**Comment by BlackScorp** [comment]
@jackyraimond just released new version, should be fixed now

**Comment by jackyraimond** [comment]
Thanks, will test it!

**Comment by luebbt** [comment]
This issue does still exists with `kiener/mollie-payments-plugin=v4.10.1` and `shopware/core=v6.5.8.14`

**Comment by BlackScorp** [comment]
@luebbt please do not use kiener/mollie-payments-plugin in composer. this is just the branch from github. please use 

composer require store.shopware.com/molliepayments  here we upload the ready for release files. but you have to add shopware store as composer repo and provide your key there

**Comment by luebbt** [comment]
@BlackScorp thank you for that hint. Ironically I replaced that package right **after** testing but did not check the issues again. This fixed all of them for me.
